version: "3"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: teste
      MYSQL_PASSWORD: root@123
    networks:
      - mysql-phpmyadmin
networks:
  mysql-phpmyadmin:

volumes:
  db_data:
